JuliaCollections/DataStructures.jl

src/hashdict.jl
also fix the version for the serialization api change
=> fix serialization ambiguity warnings

.travis.yml
Since we already have Coveralls.
=> Again add codecov

test/test_deque.jl
Tests for the iterator methods and a few for `DequeBlock`.
=> Added tests for deque

test/test_list.jl
Tested `show` and some missing methods on `Nil`s.
=> More tests for lists

test/test_deque.jl
Testing the IO methods and `empty!`.
=> More deque tests

src/containerloops.jl, src/hashdict.jl, src/sortedMultiDict.jl, src/tokens2.jl
=> Union() -> Union{}

src/accumulator.jl, test/test_accumulator.jl
=> implement values(::Accumulator)

src/DataStructures.jl, src/defaultdict.jl, src/ordereddict.jl, src/sortedDict.jl, src/sortedMultiDict.jl, src/tokens2.jl, test/test_defaultdict.jl, test/test_multidict.jl, test/test_ordereddict.jl, test/test_orderedset.jl, test/test_sortedcontainers.jl
There were a large number of statements conditional on Julia version.
=> More thorough removal of v0.3 support

src/DataStructures.jl, src/circularbuffer.jl, test/runtests.jl, test/test_circularbuffer.jl
Small patch to make tests in #144 pass.  Closes #144.
Cc: @tbreloff
=> CircularBuffer

Changelog.md
@kmsquire 
https://github.com/JuliaLang/METADATA.jl/pull/4576
=> update changelog for 0.4.3

src/accumulator.jl, src/deque.jl, src/disjoint_set.jl, src/heaps/binary_heap.jl, src/heaps/mutable_binary_heap.jl, src/ordereddict.jl, src/queue.jl, src/tokens2.jl
=> final corrections to inline docs

src/classifiedcollections.jl, test/test_classifiedcollections.jl, test/test_ordereddict.jl
Pretty sure that `pop!` wants a `ClassifiedCollections` there.
=> Fix a bug and add a few tests

doc/source/accumulators.rst
Noticed this while reviewing #188
=> Fix casing on Accumulator constructor.

src/accumulator.jl, src/hashdict.jl, src/ordereddict.jl
Just opening this PR (#187) directly from @ScottPJones's repo so that he can update directly.
> Submitted on behalf of @ScottPJones. @rawls238 @DanielArndt can you guys take a look and merge if acceptable? I'm being distracted by becoming a father and trying to get back to work.
> 
> Copy and paste from https://groups.google.com/forum/#!topic/julia-dev/_A3_HMK4EIw:
> 
> While trying to get Gadfly.jl working (and eliminating the many warning messages that come up simply trying to do "using Gadfly" under v0.5),
> I ran into the following problem in DataStructures.jl/src/accumulator.jl, that I'd like some guidance on.
> 
> The Accumulator type is simply a wrapper around a Dict.
> The issue is that in v0.5, there is a warning, because there is an outer constructor defined, which simply takes …
=> Julia v0.5, other fixes

README.rst
=> Add RTD badge to README.rst

.travis.yml, src/ordered_dict.jl
For https://github.com/JuliaLang/julia/pull/18362
=> Use isassigned(::Array) instead of isdefined(::Array)

README.rst
We are submitting coverage stats to Codecov, and many people like its interface better.
=> Add the codecov badge

REQUIRE, src/classified_collections.jl, src/deque.jl, src/int_set.jl, src/list.jl, src/multi_dict.jl, test/test_int_set.jl, test/test_ordered_dict.jl, test/test_ordered_set.jl
=> Fix Julia v0.6 xor, is deprecations

doc/source/sorted_containers.rst, src/DataStructures.jl, src/sorted_dict.jl, src/sorted_multi_dict.jl, src/sorted_set.jl, test/test_sorted_containers.jl
The function returns the type of the ordering parameter. Fixes #226
=> Added function ordtype for SortedDict, SortedMultiDict and SortedSet.

src/heaps/binary_heap.jl
=> push! on BinaryHeap now returns heap rather than nothing

src/accumulator.jl, src/ordered_dict.jl, src/sorted_dict.jl, test/test_accumulator.jl, test/test_sorted_containers.jl
=> Remove SortedDict, Accumulator ambiguity warnings/errors

src/accumulator.jl, test/test_accumulator.jl
=> Fixes #287

.travis.yml, Changelog.md, appveyor.yml
* In response to @tkelman's request (https://github.com/JuliaLang/METADATA.jl/pull/10165#issuecomment-313841694)
* Compat still needed to support v0.5
=> Drop v0.4 support

test/test_sorted_containers.jl
* (Didn't seem to cause any problems...)
=> Remove stray quotes from test_sorted_containers.jl

src/balanced_tree.jl, src/circ_deque.jl, src/circular_buffer.jl, src/default_dict.jl, src/deque.jl, src/disjoint_set.jl, src/heaps/binary_heap.jl, src/heaps/mutable_binary_heap.jl, src/multi_dict.jl, src/ordered_dict.jl, src/ordered_set.jl, src/priorityqueue.jl, src/sorted_dict.jl, src/sorted_multi_dict.jl, src/sorted_set.jl, src/tokens2.jl, src/trie.jl, test/REQUIRE, test/runtests.jl, test/test_accumulator.jl, test/test_circ_deque.jl, test/test_circular_buffer.jl, test/test_classified_collections.jl, test/test_deque.jl, test/test_list.jl, test/test_ordered_dict.jl, test/test_ordered_set.jl, test/test_sorted_containers.jl, test/test_sorting.jl
Remove old code for 0.4 and 0.5-.
=> Fix most of 0.7 depwarns

.travis.yml, REQUIRE, appveyor.yml
Once this is merged, FemtoCleaner will take care of the rest
=> Drop support for 0.5

test/README, test/runtests.jl, test/test_accumulator.jl, test/test_binheap.jl, test/test_circ_deque.jl, test/test_circular_buffer.jl, test/test_classified_collections.jl, test/test_deque.jl, test/test_disjoint_set.jl, test/test_int_set.jl, test/test_list.jl, test/test_multi_dict.jl, test/test_mutable_binheap.jl, test/test_ordered_dict.jl, test/test_ordered_set.jl, test/test_sorted_containers.jl, test/test_sorting.jl, test/test_stack_and_queue.jl, test/test_trie.jl
* Also, remove DataStructure, Test inputs from test files
* These were there to allow running the tests directly from the command line
* To run the tests from the command line now, use `julia test/runtests.jl xxx`
to run `test_xxx.jl`
* Added README to specify this
=> Convert remaining tests use testsets

src/delegate.jl
Replaces https://github.com/JuliaCollections/DataStructures.jl/pull/328
=> Fix loading on 0.7

doc/source/accumulators.rst, doc/source/sorted_containers.rst, src/default_dict.jl, src/ordered_set.jl, test/test_ordered_dict.jl
Turns out to be pretty straight forward...
This pass all the test on master without any unexpected depwarns. Passing on CI probably need a nightly update.....
=> Fix depwarns and errors on 0.7

src/sorted_dict.jl, test/test_sorted_containers.jl
This matches most other Associative collections.
=> add get!(func, ::SortedDict, key)

docs/src/accumulators.md, docs/src/circ_buffer.md, docs/src/default_dict.md, docs/src/disjoint_sets.md, docs/src/priority-queue.md, docs/src/trie.md
=> Minor doc fix

docs/src/default_dict.md, src/default_dict.jl, test/test_default_dict.jl
I find I want the default value to be some function on the key pretty often. Motivating example added to the docs.
Is there a better name than `passkey`?
~EDIT: Oops, still need to add a few tests~
=> Add argument to Default*Dict to tell it to pass the key to the default function

src/DataStructures.jl
=> Use deprecated bindings from Base for deprecations

src/circular_buffer.jl, test/test_circular_buffer.jl
=> circbuff fix

docs/src/priority-queue.md, src/priorityqueue.jl
=> Fix PriorityQueue construction doc and docstring

docs/src/circ_buffer.md, src/circular_buffer.jl, test/test_circular_buffer.jl
=> Fill CircularBuffer

test/test_circular_buffer.jl
Contributes towards fixing #412
=> Add  nested testsets to CircularBuffer

docs/src/accumulators.md, src/accumulator.jl, src/classified_collections.jl, test/test_accumulator.jl
=> Modify Accumulator constructor

test/test_accumulator.jl, test/test_binheap.jl, test/test_circ_deque.jl, test/test_circular_buffer.jl, test/test_classified_collections.jl, test/test_default_dict.jl, test/test_deque.jl, test/test_disjoint_set.jl, test/test_int_set.jl, test/test_list.jl, test/test_multi_dict.jl, test/test_mutable_binheap.jl, test/test_ordered_dict.jl, test/test_ordered_set.jl, test/test_priority_queue.jl, test/test_queue.jl, test/test_sorted_containers.jl, test/test_sorting.jl, test/test_stack.jl, test/test_trie.jl
=> More nested testsets

docs/src/priority-queue.md, src/priorityqueue.jl, test/test_priority_queue.jl
=> delete! for PriorityQueue

docs/src/sorted_containers.md
=> Change Associative to AbstractDict

src/circular_buffer.jl, test/test_circular_buffer.jl
=> Fix confusion in circular buffer

docs/src/accumulators.md
we deprecated `push!` a while ago,
but forgot to update the docs.
=> Update docs for accumulator

docs/make.jl
Missed that this had to be updated in #450.
=> Update docs/make.jl to include mutable_linked_list.md

docs/src/mutable_linked_list.md, src/mutable_list.jl, test/test_mutable_list.jl
Thought this might be useful to have.
=> Add support for range indexing into MutableLinkedLists

docs/src/heaps.md, src/heaps.jl, src/heaps/mutable_binary_heap.jl, test/test_mutable_binheap.jl
=> Added `delete!(node_handle)` functionality for mutable binary heaps

src/circular_buffer.jl, test/test_circular_buffer.jl
=> CircularBuffer(n)

.gitignore, Project.toml, src/DataStructures.jl, src/accumulator.jl, src/heaps/binary_heap.jl, src/int_set.jl, src/queue.jl, src/sorted_multi_dict.jl, src/sorted_set.jl, src/stack.jl, test/test_binheap.jl, test/test_queue.jl, test/test_stack.jl
I have just registered for  release 0.14.2
we keep making releases without dropping deprecations.
So release 0.15 will accumulate several years of deprecations,
and just get it done.
Closes #477
=> Prepare to release v0.15.0

docs/src/priority-queue.md
This is a very useful function, which is currently not documented here, so I have added it. Thanks to @sbromberger for this beautiful function!
(P.S. I am new to Open Source contributing. Sorry if I have done anything incorrect.)
=> Added documentation for `dequeue_pair!`

src/heaps.jl, src/heaps/binary_heap.jl, src/heaps/minmax_heap.jl, src/heaps/mutable_binary_heap.jl, test/test_binheap.jl, test/test_minmax_heap.jl, test/test_mutable_binheap.jl
Fixes #518. Do we need to test these methods?
=> Implement sizehint! for heaps

Project.toml, src/circular_buffer.jl, test/test_circular_buffer.jl
With less call indirection and calculations.
=> CircularBuffer: Added first/last methods that slightly improve performance

src/circular_buffer.jl
I improved docstring in circular_buffer.jl to fix #510
=> improved docstring in circular_buffer.jl

src/deque.jl
I realized the deque.jl is missing some docstrings like #549. So I improved it.
=> improved docstrings in deque.jl

src/fenwick.jl
Just adding some missed type annotation of fenwick.jl
=> improved docstrings of fenwick.jl

src/accumulator.jl
Update docstrings of Accumulator and clean up codes based on its docstrings.
=> update docstrings of Accumulator and clean up codes based on its docstrings.

README.md, docs/src/index.md
=> E.g. RobinDict in docs

Project.toml, docs/src/circ_deque.md, docs/src/deque.md, docs/src/stack_and_queue.md, src/DataStructures.jl, src/circ_deque.jl, src/deprecations.jl, src/deque.jl, src/queue.jl, src/stack.jl, test/test_circ_deque.jl, test/test_deque.jl, test/test_queue.jl, test/test_stack.jl
Changes made in docs,src and test folders
=> Use first and last, rather than front, back, top etc

src/disjoint_set.jl, test/test_disjoint_set.jl
Add additional `DisjointSets` constructors to address: #562.
=> Add additional constructors for DisjointSets

src/disjoint_set.jl
I improved docstrings for disjoint_set.jl
=> improved docstrings for disjoint_set.jl

Project.toml, src/deprecations.jl, src/deque.jl
=> Deprecate `deque` constructor

Project.toml, src/heaps/mutable_binary_heap.jl, test/test_mutable_binheap.jl
=> Fix out of bounds access in _binary_heap_pop!

Project.toml, src/DataStructures.jl, src/deque.jl, test/bench_deque.jl, test/test_deque.jl
=> Remove deprecated deque method

Project.toml, src/sparse_int_set.jl, test/test_sparse_int_set.jl
=> Remove overloading of 0 arg zip()

src/robin_dict.jl, test/test_robin_dict.jl
=> Add merge function to RobinDict

Project.toml, src/ordered_robin_dict.jl
=> Fix the overloaded docs in v0.18.1

src/list.jl, test/test_list.jl
=> heterogeneous elements promoted during list construction

docs/src/disjoint_sets.md
The function defined in `src` ends by a `!`
=> find_root -> find_root!

Project.toml, docs/make.jl, docs/src/disjoint_set.md
Put this together in response to #708. Original discussion didn't get much input, but I am definitely open to modifying this and/or creating another PR if others feel that changes ought to be made.
=> Fix docs mistake with respect to DisjointSet

test/test_mutable_binheap.jl
Found some misformatted code in `test_mutable_binheap.jl` while working on #712, thus opening a PR.
=> fix linting in test_mutable_binheap.jl

src/heaps/arrays_as_heaps.jl, src/heaps/binary_heap.jl
This forward-ports @ChrisRackauckas  PR #747 
It does not require review as that PR was already reviewed.
Just running it here to be sure CI doesn't fail
=> ForwardPort: inline a bit to remove an inference trigger

docs/src/priority-queue.md
As discussed in #749 here is my proposal to document this functionality.
=> Documentation for key/value iteration over PriorityQueue

.github/workflows/Documenter.yml
seems like the documenter action was failing i think this might fix it
=> documenter indentation

src/circular_buffer.jl, test/test_circular_buffer.jl
Since #548 seems stale although being basically finished, except for a clean commit history, I'm just opening a new PR to get this merged.
=> Implement resize! for CircularBuffer

src/circular_buffer.jl, test/test_circular_buffer.jl
=> Proposed bug fix for bad state when using CircularBuffer push!

docs/src/priority-queue.md, src/priorityqueue.jl
Following #800  in the series of documentation PRs. Changes in this PR are analogous to the ones in #800
=> Improved Priority Queue Documentation + docstrings

src/robin_dict.jl
Let me know if you think a test is required here. I didn't add one as the only side effects are extra allocations in some cases which wouldn't make for a particularly reliable test.
=> Resize to new size. Fixes #788

Project.toml, src/robin_dict.jl
@oxinabox should I bump up the version and release this?
=> [Backport] Bugfix for resize in RobinDict

.github/workflows/CI.yml, .github/workflows/TagBot.yml
I am not sure if this is necessary but perhaps it will  help ensure future releases get a tag again...
=> Update CI for release-0.18 branch

.github/workflows/Documenter.yml
Taken from https://github.com/julia-actions/julia-docdeploy README
=> CI: update Documenter job to latest version

CHANGELOG.md, Project.toml
=> Prep for v0.19.1
