.travis.yml
Perhaps better to update the default Travis script, but for now.
=> Get coverage data generation back up for Coveralls

src/DataStructures.jl, src/defaultdict.jl, src/disjoint_set.jl, src/hashdict.jl, src/ordereddict.jl, src/orderedset.jl, test/test_ordereddict.jl, test/test_orderedset.jl
* Plus minor related changes
Eventually, these data structures might be made moot, if https://github.com/JuliaLang/julia/pull/10116 is merged.  But for now, it would at least be worthwhile matching `Dict` and `Set` construction in base in Julia v0.3.
I plan to merge this in a day or two, pending any comments.
=> RFC: Update OrderedDict, OrderedSet constructors to take iterables (fixes #50, #64, #67)

README.rst, REQUIRE, src/DataStructures.jl, src/heaps.jl, test/test_binheap.jl
Python's heapq module offers two convenient functions, [`nlargest` and `nsmallest`](https://docs.python.org/2/library/heapq.html#heapq.nlargest). This patch replicates part of that functionality (the `key` argument is missing − it should probably be a feature of the underlying heap). 
For performance reasons I added an `extract_all_rev!` method, but since `extract_all` wasn't documented in `README.md` I didn't document it either. I also added relevant tests in `test_binheap.jl`.
=> Implement nlargest and nsmallest

src/defaultdict.jl, src/disjoint_set.jl, src/hashdict.jl, src/ordereddict.jl, src/sortedDict.jl, src/trie.jl, test/test_mutable_binheap.jl, test/test_sorteddict.jl
Cleaning up from the tuples carnage, this gets the package passing on 0.4 without any deprecation warnings.
=> 0.4 compat fixes

src/DataStructures.jl
Fix a newly added deprecation warning in Julia master.
=> Fix warning about {A, B...}

src/defaultdict.jl, src/hashdict.jl, test/test_ordereddict.jl
Make `collect` return an array of `Pair`s, fixes unit tests.
~~Fixed `IntSet` deprectation warning for `status()` of `SortedDict`.~~(not necessary after rebase)
=> fix Pair usage for ordereddict

src/DataStructures.jl, src/multidict.jl, test/runtests.jl, test/test_multidict.jl
This is an updated version of https://github.com/JuliaLang/DataStructures.jl/pull/90 that is ready to merge. The main change is that `setindex!` has been replaced with `insert!`, in analogy with `SortedMultiDict`. cc @wildart
=> Add Multidict

src/DataStructures.jl, src/queue.jl, src/stack.jl, test/test_stack_and_queue.jl
which returns an array with Stack elements in LIFO order/Queue elements in FIFO order.
This is essentially the fix for https://github.com/JuliaLang/DataStructures.jl/issues/116
This PR only adds the iter method with LIFO semantics for Stack and FIFO semantics for queue. 
The Stacks and Queues are still parametrized by the underlying container (Deque{T}) than the element type. I think these datastructures should ideally be parametrlized by the element type, and not implementation details which causes an abstraction leak. 
However I have *not* changed this in this PR's code, only added an iter method which returns an array with the elements in an order that makes sense for the datastructure - LIFO for Stack and FIFO for queue. I finally went with @lindahua 's concept than by implementing …
=> added iter method to stack and queue

src/DataStructures.jl
Passed `Pkg.test` on 0.4. Needed to resolve dependencies during precompilation.
=> Add precompile directive

README.rst, src/DataStructures.jl, src/containerloops.jl, src/sortedDict.jl, src/sortedMultiDict.jl, src/sortedSet.jl, src/tokens2.jl, test/test_sortedcontainers.jl
In order to be compatible with dict, the eltype(.) function for
SortedDict and SortedMultiDict now returns Pair{K,V} instead
of Tuple{K,V}.  This requires a host of other changes.
=> Change eltype of sorted containers to Pair{}

src/list.jl, test/test_list.jl
Bugfix to issue #135 : `list(x)==list(x)` returns false.
With this implementation, `nil(T) == nil(S)` is `true` for all types `T` ans `S`. This follows the same equality rule as in arrays : `T[] == S[]`.
When `x::Cons` and `y::Cons`, we compare `x.head` and `y.head` and call `==` recursively on the tails of `x` and `y`.
All other equality rules for lists can be implemented implicitly as a generic fallback to `Base.===`.
Tests included.
=> Fix #135, define ==(x::Nil, y::Nil) and ==(x::Cons, y::Cons)

README.rst
- The triple tick does not work in rst
- Seems that github doesn't support the code-block or code directive, so
although this won't have syntax highlighting, it is no worse than what
is currently displayed.
=> Remove invalid rst and align elements

src/hashdict.jl, test/test_ordereddict.jl
The signature of `write` changed a bit in Julia 0.4, and using `SerState` (ie. `Base.Serializer.SerializationState`) directly doesn't work. `s.io` works in 0.4 but wouldn't be backwards compatible with Julia 0.3.
Using the `serialize` method provided in the Julia distribution will allow the base library to make the appropriate call.
=> Serialize & deserialize hashdicts in Julia 0.4

.travis.yml, README.rst, REQUIRE, src/DataStructures.jl, src/containerloops.jl, src/defaultdict.jl, src/hashdict.jl, src/multidict.jl, src/ordereddict.jl, src/orderedset.jl, src/sortedDict.jl, src/sortedMultiDict.jl, src/sortedSet.jl, src/tokens2.jl, src/trie.jl, test/test_deque.jl, test/test_ordereddict.jl, test/test_sortedcontainers.jl, test/test_trie.jl
This subsumes #146, and further removes all uses of `@compat`.  
Closes #145 
Will merge tonight or tomorrow (PST) if there are no comments.
=> Remove support for v0.3

src/hashdict.jl, src/ordereddict.jl, test/test_ordereddict.jl
* Add more generic version of construction from Pairs, to allow
mixed type Pairs
* Relax type constraints on HashDict (which is used as the basis
for OrderedDict), to allow mixed type Pairs
=> Fix OrderedDict constructors (fixes #148)

src/deque.jl, test/test_deque.jl
fixes #152.
Also offers a hash.
Both of these are different if the blksize is different. Perhaps this is not desired?
=> Add hash and == for Deque.

src/queue.jl, src/stack.jl, test/test_stack_and_queue.jl
This is a resubmission of #98, which I was too slow to merge before.  It's a minor change, and if there's reason not to do this, it can easily be reverted later.  But it's a small step in the right direction to cleaning up `Stack` and `Queue` (and `Deque`) types.
(Original PR from @andrewcooke; he still owns the commit.)
=> RFC: change type to hide implementation

src/DataStructures.jl
* The latest of these was added 8 months ago, which is probably long
enough for most packages to adapt
* The corresponding deprecations in Julia itself have been removed
* In the future, these should include the specific DataStructures/
julia version when added and/or when to remove
=> RFC: Delete deprecation warnings

src/DataStructures.jl, src/defaultdict.jl, src/hashdict.jl, src/heaps.jl, src/intset.jl, src/multidict.jl, src/ordereddict.jl, src/orderedset.jl, test/test_intset.jl, test/test_ordereddict.jl, test/test_orderedset.jl
This is simply a search and replace. 
The deprecation for `sizehint` is actually handled by the definition in `Base`.
Should not be controversial.  Will merge soon.
=> In Julia 0.4: sizehint => sizehint! (and sizehint is deprecated).  Fixes #119.

test/runtests.jl, test/test_accumulator.jl, test/test_binheap.jl, test/test_defaultdict.jl, test/test_disjoint_set.jl, test/test_intset.jl, test/test_list.jl, test/test_multidict.jl, test/test_mutable_binheap.jl, test/test_ordereddict.jl, test/test_sortedcontainers.jl, test/test_stack_and_queue.jl, test/test_trie.jl
@kmsquire 
this cleans up the tests a bit so that most of the imports are done in `runtests` instead of duplicated across test files
=> move imports to runtests

src/defaultdict.jl, src/deque.jl, src/hashdict.jl, src/sortedDict.jl, test/test_defaultdict.jl, test/test_deque.jl, test/test_intset.jl, test/test_sortedcontainers.jl, test/test_stack_and_queue.jl
Cleaning up `error` functions.
In cases where the correct exception seemed ambiguous (e.g., `pop!` on an empty `Deque`), I followed conventions in `Base`.
=> RFC: Use "throw" with a specific exception instead of "error()"

src/DataStructures.jl, src/dictsupport.jl, src/hashdict.jl, src/ordereddict.jl, src/orderedset.jl, test/test_ordereddict.jl
* https://github.com/JuliaLang/julia/pull/10116
* This is largely copy and paste + rename, fixups
* Offers good speed improvements in `OrderedDict` iteration, small improvements elsewhere
(The biggest speedup in iteration--compacting the storage before iterating--also gave a good speedup to the previous `OrderedDict` version here.  But this version is still faster and cleaner.)
I plan to remove `HashDict` and clean up `DefaultDict` in another PR in the near future, but I felt it better to put this in separately.
Cc: @JeffBezanson
=> Port of @JeffBezanson's ordered dict

src/orderedset.jl, test/test_orderedset.jl
Discussed here: https://github.com/JuliaLang/DataStructures.jl/issues/178
=> Add indexing to OrderedSets

doc/source/stack_and_queue.rst, src/DataStructures.jl, src/deque.jl, src/queue.jl, src/stack.jl, test/test_stack_and_queue.jl
@kmsquire
This moves the iterator for stack and queue to conform to iterators such as those in https://github.com/JuliaLang/Iterators.jl
It effectively just calls down and utilizes the iterator for `Deque`
=> use standard iterator for Stack + Queue Fixes #116

doc/source/disjoint_sets.rst, src/DataStructures.jl, src/disjoint_set.jl, test/test_disjoint_set.jl
For `DisjointSets`, it is useful if `union!` can return the root of the newly merged set. 
For example, it is used in implementing elimination tree for sparse factorization.
(See Algorithm 5.1 of [2])
The implementation of `_union!` is based on [1].  
After this merge, we have 
```julia
julia> a = IntDisjointSets(10)
DataStructures.IntDisjointSets([1,2,3,4,5,6,7,8,9,10],[0,0,0,0,0,0,0,0,0,0],10)
julia> union!(a, 3, 5)
3
julia> a
DataStructures.IntDisjointSets([1,2,3,4,3,6,7,8,9,10],[0,0,1,0,0,0,0,0,0,0],9)
```
References: 
[1] Data Structures and Network Algorithms, Robert Tarjan (1983) Chapter 2 
Disjoint Sets [[url]](http://epubs.siam.org/doi/abs/10.1137/1.9781611970265.ch2)
[2] The Role of Elimination Trees in Sparse Factorization, Joseph W.H. Liu …
=> For DisjointSets, make union! return the root of the newly merged set

src/containerloops.jl, src/trie.jl
- Add `length` functions for SDM iterators
- Add `iteratorsize` iterator trait introduced in https://github.com/JuliaLang/julia/commit/a2ce2309863564aed3fba4f8927d586b11983219
=> Fix tests in Julia 0.5

src/int_set.jl, test/REQUIRE, test/runtests.jl, test/test_circular_buffer.jl, test/test_multi_dict.jl, test/test_ordered_dict.jl
Added `complement` and `complement!`. Fixing tests now. Comments and suggestions welcome as I go along.  
Fixes #209 
cc: @kmsquire @phaverty @tkelman
=> WIP: Get things working on v0.5

REQUIRE, doc/source/circ_deque.rst, doc/source/index.rst, src/DataStructures.jl, src/circ_deque.jl, test/REQUIRE, test/runtests.jl, test/test_circ_deque.jl, test/test_circular_buffer.jl, test/test_classified_collections.jl, test/test_deque.jl, test/test_ordered_set.jl
The main attraction of `CircularDeque` is its performance:
```julia
julia> using DataStructures, BenchmarkTools
julia> D = Deque{Int}()
Deque [Int64[]]
julia> C = CircularDeque{Int}(5)
CircularDeque{Int64}([])
julia> function foo!(D)
for i = 1:5
push!(D, i)
end
v = back(D)
for i = 1:5
shift!(D)
end
v
end
foo! (generic function with 1 method)
julia> foo!(D)
5
julia> foo!(C)
5
julia> @benchmark foo!($D)
BenchmarkTools.Trial: 
samples:          10000
evals/sample:     870
time tolerance:   5.00%
memory tolerance: 1.00%
memory estimate:  0.00 bytes
allocs estimate:  0
minimum time:     153.00 ns (0.00% GC)
median time:      155.00 ns (0.00% GC)
mean time:        156.19 ns (0.00% GC)
maximum time:     265.00 ns (0.00% GC)
julia> @benchmark foo!($C)
BenchmarkTools.Trial: 
samples: …
```
=> Add a Deque based on a circular buffer

src/DataStructures.jl, src/dict_sorting.jl, test/runtests.jl, test/test_sorting.jl
* Also define `sort(d::Dict)` to yield an `OrderedDict`
Supersedes #43
=> RFC: Allow sorting on OrderedDicts

src/accumulator.jl
Accumulator can be immutable -- the contents of the `map` changes, the `map` never does.
`immutable` should be preferred to `type` where possible, as it is more performant.
And accumulator should be a subtype of Associative -- because it is.
This lets it be used as a dispatch.
=> Make Accumulator an immutable subtype of Associative

src/DataStructures.jl, src/default_dict.jl, test/test_default_dict.jl
* `Dict` and `OrderedDict` constructors have changed, and
`DefaultDict`/`DefaultOrderedDict` haven't kept up.
* The changes:
Dict(KeyType, ValType) => Dict{KeyType, ValType}()
Dict(ks, vs) is deprectated
* This deprecates working versions of these from DefaultDict
and friends, and fixes broken calls which attempt to
use these old constructors.
=> RFC: Deprecate or fix old/broken DefaultDict constructors

src/DataStructures.jl, src/default_dict.jl, src/dict_support.jl, src/hash_dict.jl, test/REQUIRE, test/test_circ_deque.jl, test/test_priorityqueue.jl
This reverts commit 1681e24c8813013d5d469a3cb5fa5ff65a0a3f3e.
cc @kmsquire, https://github.com/JuliaLang/DataStructures.jl/pull/224 managed to break Gadfly with a `no method matching push!(::Gadfly.Guide.##86#91, ::Tuple{Array{Compose.Context,1},Int64}}`
=> Revert "Remove HashDict"

src/circular_buffer.jl, test/test_circular_buffer.jl
Hi,
This PR adds `unshift!` to circular buffers. I've also `@testset`-ified the tests, and added tests of unshifting items.
On an unrelated note, I notice that the extended functions for `CircularBuffer` (push, getindex, setindex etc.) are not `@inline`. Is there any point in inlining these?
Cheers,
K
=> Add Base.unshift! for CircularBuffers

src/circ_deque.jl, test/test_circ_deque.jl
Hi,
This PR simply adds the `start`/`next`/`done` methods required for idiomatic for-loop iteration over CircularDeques.
I'm a relative Julia novice, so any tips (especially regarding performance) are appreciated.
Cheers,
Kevin
=> Implement start/next/done for CircularDeque

src/default_dict.jl, src/delegate.jl, test/test_default_dict.jl
* When called on an `Associative` container, `sizehint!`, `empty!`, and
`setindex!` all return the container
* The `@delegate` macro is not aware of this, and instead returned
the wrapped object when used to define, e.g., `DefaultDict`s
* Fixed by creating a second macro, `@delegate_return_parent`,
which works like `@delegate`, but returns the parent container.
**Edit:** `delete!` also returns the container.
=> RFC: Fix delegation for *Dict functions returning the underlying *Dict

.travis.yml, src/balanced_tree.jl, src/circ_deque.jl, src/classified_collections.jl, src/default_dict.jl, src/deque.jl, src/heaps.jl, src/heaps/binary_heap.jl, src/heaps/mutable_binary_heap.jl, src/ordered_dict.jl, src/priorityqueue.jl, test/test_mutable_binheap.jl, test/test_priorityqueue.jl, test/test_sorted_containers.jl
Is there a better way to handle the new `where` syntax than `eval(parse(...))`?
=> Julia 0.6 fixes

src/default_dict.jl
* eval was being used to create the `DefaultDict` type, because it required some v0.6 specific changes.  
However, with `@compat`, eval isn't needed (unless I missed something?)
(The actual change to the constructor itself is needed, though!)
Cc: @andreasnoack
=> RFC: Remove eval from DefaultDict constructor

doc/source/sorted_containers.rst, src/sorted_dict.jl, src/sorted_multi_dict.jl, src/sorted_set.jl, test/test_sorted_containers.jl
This allows one to write constructors without specifying an ordering, e.g.:
``` julia
SortedDict{Int, Int}()
SortedMultiDict{Int, Int}()
SortedSet{Int}()
```
Defaults to `Forward` ordering.  Fixes #134.
Cc: @StephenVavasis
=> RFC: Add default 2-type argument constructors to sorted collections

src/default_dict.jl, src/ordered_dict.jl, src/sorted_dict.jl, src/sorted_multi_dict.jl, test/test_default_dict.jl, test/test_ordered_dict.jl, test/test_sorted_containers.jl
I tried to match the tone from Base, but please let me know if anything sounds off.
=> Add warning on unordered to ordered conversion. Fixes #216

src/heaps/binary_heap.jl
The `valtree` in the binary heap is not strictly typed. In some codes I have, this causes a 2x performance reduction in the entire code (<.1% is data structure related) due to checking if a binary heap is empty. The simple fix is to make it `Vector{T}` instead of the non-concerete `Array{T}`.
Reference for performance problems: https://github.com/JuliaDiffEq/StochasticDiffEq.jl/issues/13
=> Fix typing in Binary Heap

doc/source/heaps.rst, src/DataStructures.jl, src/heaps.jl, src/heaps/mutable_binary_heap.jl, test/test_mutable_binheap.jl
Fixes #217: add an interface to get the handle of the top element of a mutable binary heap, in order to be able to call `update!` on it.
=> Add top_with_handle(::MutableBinaryHeap) function

REQUIRE, src/container_loops.jl, src/heaps.jl, src/list.jl, src/tokens.jl
~~**DO NOT MERGE NOW!!!!**~~
~~This requires https://github.com/JuliaLang/Compat.jl/pull/325 and a new tag. I'm using this (and other) PR's to check if the implementation is correct.~~
Ready now.
=> Fix 0.6 abstract type declaration depwarn

doc/source/sorted_containers.rst, src/sorted_set.jl, test/test_sorted_containers.jl
* `SortedSet` constructors can now take nothing, an ordering, an iterable,
or an ordering and an interable, with or without specifying the set
element type
=> RFC: Update `SortedSet` constructors

src/sorted_multi_dict.jl, test/runtests.jl
This fixes the following:
```julia
julia> using Base.Test, DataStructures
INFO: Recompiling stale cache file /home/tim/.julia/lib/v0.5/DataStructures.ji for module DataStructures.
julia> detect_ambiguities(Base,Core,DataStructures)
Skipping Base.<|
Skipping Base.>:
Skipping Base.cluster_manager
1-element Array{Tuple{Method,Method},1}:
((::Type{DataStructures.SortedMultiDict}){K,D}(ps::Pair{K,D}...) at /home/tim/.julia/v0.5/DataStructures/src/sorted_multi_dict.jl:49,(::Type{DataStructures.SortedMultiDict})(kv) at /home/tim/.julia/v0.5/DataStructures/src/sorted_multi_dict.jl:72)
```
Noticed in https://github.com/JuliaImages/ImageMetadata.jl/issues/13. Will need a new tag for ImageMetadata to pass its tests.
=> Fix an ambiguity

src/sorted_set.jl, test/test_sorted_containers.jl
SortedSet has a couple of constructors which look like
```julia
SortedSet(o::Ordering, iter) = sortedset_with_eltype(o, iter, eltype(iter))
SortedSet(iter, o::Ordering=Forward) = sortedset_with_eltype(o, iter, eltype(iter))
```
Because this causes an ambiguity to be shown on Julia v0.4, the following constructor was added for that version only:
```julia
SortedSet(o1::Ordering,o2::Ordering) =
throw(ArgumentError("SortedSet with two parameters must be called with an Ordering and an interable"))
```
However, DataStructure tests recently started testing for ambiguities, and the lack of this definition on v0.5 and v0.6 causes problems.  So this PR just defines it for all julia versions.
=> Fix SortedSet ambiguities on julia v0.5, v0.6

src/accumulator.jl, test/test_accumulator.jl
Before:
```julia
julia> using DataStructures
julia> counter([2,3,4]) == counter([2,4,3]) 
ERROR: MethodError: no method matching get(::DataStructures.Accumulator{Int64,Int64}, ::Int64, ::Symbol)
Closest candidates are:
get(::ObjectIdDict, ::ANY, ::ANY) at dict.jl:284
get(::AbstractArray{T,N}, ::Integer, ::Any) at abstractarray.jl:912
get{K,V}(::Dict{K,V}, ::Any, ::Any) at dict.jl:692
...
in in(::Pair{Int64,Int64}, ::DataStructures.Accumulator{Int64,Int64}, ::Base.#==) at ./dict.jl:10
in ==(::DataStructures.Accumulator{Int64,Int64}, ::DataStructures.Accumulator{Int64,Int64}) at ./dict.jl:209
```
Now:
``julia
julia> using DataStructures
julia> counter([2,3,4]) == counter([2,4,3]) 
ERROR: MethodError: no method matching get(::DataStructures.Accumulator{Int64,Int64}, ::Int64, ::Symbol) …
=> EqualityForAccumulators

src/dict_support.jl, src/sorted_dict.jl
~~This function was moved to dict_support.jl, but wasn't removed from its original location.~~
=> Move not_iterator_of_pairs function from sorted_dict.jl to dict_support.jl

appveyor.yml, test/test_classified_collections.jl, test/test_sorted_containers.jl
The sum of the first 5000 primes overflows an `Int32`.  The easy fix was to force it to be an `Int64`.
=> Fix an overflow in testing SortedDicts on 32-bit systems

src/DataStructures.jl, src/sorted_multi_dict.jl, test/test_sorted_containers.jl
Update SortedMultiDict constructors to accept type parameters
* Mirrors recent updates to SortedDict constructors
@StephenVavasis, can you please review?
One change, mirrored in all of the other `Dict`s, is that I deprecated `SortedMultiDict(ks,vs)` (constructor from arrays).  However, `SortedMultiDicts` are different enough that I would like feedback on that change (and anything else.)
=> RFC: SortedMultiDict constructor updates

src/accumulator.jl, test/test_accumulator.jl
Accumulator was overly strictly typed.
This was breaking the ability to use it for `SubString`s and `String`s interchangeably.
There is no need to type-things any stricter than the backing dictionary does.
=> Reduce type strictness for accumulator

src/DataStructures.jl, src/priorityqueue.jl, test/test_priorityqueue.jl
Closes #289. Adds dequeue_with_val! to PriorityQueue - returns a tuple (key, value). Implemented also for specific dequeuing of a known key.
=> dequeue_with_val! - closes #289

src/disjoint_set.jl, test/test_disjoint_set.jl
This is my attempt to resolve #294
=> fix broken find_root for non-int disjoint sets

src/DataStructures.jl
* For a short while, a seprate `iter` function was defined for
Stacks and Queues.  This was deprecated in favor of iterating
over Stacks and Queues directly (which is more standard in Julia)
=> RFC: Remove v0.6 deprecations

REQUIRE, src/DataStructures.jl, src/tokens.jl
* Will likely need to be reintroduced in the future, but for now, all is up to date with v0.6/v0.7
Probably good to add this before tagging.
=> Remove Compat

README.rst
I had to reenable Coveralls; it was enabled for JuliaLang/DataStructures.jl but not for JuliaCollections/DataStructures.jl. This also removes the 0.5 badge since we've dropped support for it.
=> Update README badges for repo move

src/DataStructures.jl
* This previously worked, and was broken with the release of DataStructures v0.7
=> Added deprectation for PriorityQueue{K,V,ForwardOrdering}()

src/heaps/binary_heap.jl, src/heaps/mutable_binary_heap.jl
This will allow `@inbounds` to propagate into this call.
=> `@inline` binary heap `top` call

src/DataStructures.jl, src/accumulator.jl, test/test_accumulator.jl
This resolves https://github.com/JuliaCollections/DataStructures.jl/issues/303
and https://github.com/JuliaCollections/DataStructures.jl/issues/285
In particular it gets rid of `pop!` entirely for `dec!`, with a deprecation warning.
After the deprecation period is over, we can add `pop!` back for the Bag/multiset interpretation of an accumulator.
And then maybe add it as thing that all ClassifiedCollections have too,
(since then all of them will have that)
Possibly `reset!` should be named `delete!` and should have the normal `delete!` return value of the whole collection. Right now it returns the count of the deleted item. Like `pop!`
It added new exports for `inc!`, `dec!` and `reset!`.
Technically if wanted to reduce exports `inc` could stay as `push!`, and `reset!` could be come …
=> Make counters use inc!, dec!, reset! and merge!, also adds setindex!

src/default_dict.jl, src/ordered_dict.jl
...in argument types of `in` and `next` on newer Julia versions.
Admittedly, I don't know whether the `KeySet` interface promises anything that DataStructures currently doesn't hold, but at least this makes DataStructures load again on Julia 0.7.
=> Use KeySet instead of KeyIterator

test/test_int_set.jl
Fixes the
```
WARNING: deprecated syntax "implicit assignment to global variable `x`".
Use "global x" instead.
```
when running the tests.
=> Remove unnecessary `global` declaration in IntSet test

docs/src/circ_buffer.md, src/circular_buffer.jl, test/test_circular_buffer.jl
Previously we had only `push!` and `unshift!`; this PR adds the corresponding deletion operations.  I also modified the existing code to allocate the entire underlying buffer up-front, and to introduce an explicit length field.  This ensures that `shift!` and `unshift!` run in O(1) time, rather than O(n).
I also noticed that most accesses to `cb.buffer` could safely be annotated `@inbounds`, since the `CircularBuffer` code already performs its own bounds-checking, but I'll save that for another PR.
=> Add implementations of pop! and shift! to CircularBuffer

src/accumulator.jl, src/ordered_set.jl, test/test_ordered_set.jl
Comments for fixes: 
* unlike `_default_eltype` function, macro `@default_eltype` accepts iterator, not type
* since `keys()` for `OrderedSet` should mimic array indexing, it's keys should be integers in range `1:length(s)`, not keys of an underlying dict, which are just elements of the set
There's still a couple of deprecation warnings, but tests pass locally.
=> Fixed keys() and findfirst()

src/DataStructures.jl, src/accumulator.jl, test/test_accumulator.jl
This is basically #198 but with select and sort.
And up to date and without conflicts.
I left off optimising the `most_common(A, 1)` case, because that optimization should be done to
`select` in Base.
I think
=> add most_common for accumulator

src/accumulator.jl, src/circ_deque.jl, src/classified_collections.jl, src/default_dict.jl, src/deque.jl, src/int_set.jl, src/multi_dict.jl, src/ordered_dict.jl, src/ordered_set.jl, src/priorityqueue.jl, src/queue.jl, src/stack.jl, src/trie.jl, test/runtests.jl
This makes DataStructures functional in face of the new iteration protocol and resolves all the occurring ambiguities.
=> Compatibility with new iteration protocol

src/circular_buffer.jl
Timings:
Before:
```
julia> using DataStructures
julia> using BenchmarkTools
julia> cb=CircularBuffer{Float64}(3)
0-element DataStructures.CircularBuffer{Float64}
julia> pusher(cb)=(@inbounds for i=1:10^6; push!(cb, 3.);end; nothing)
pusher (generic function with 1 method)
julia> @benchmark pusher(cb)
BenchmarkTools.Trial:
memory estimate:  0 bytes
allocs estimate:  0
--------------
minimum time:     6.944 ms (0.00% GC)
median time:      6.995 ms (0.00% GC)
mean time:        7.029 ms (0.00% GC)
maximum time:     8.994 ms (0.00% GC)
--------------
samples:          713
evals/sample:     1
```
After:
```
julia> @benchmark pusher(cb)
BenchmarkTools.Trial:
memory estimate:  0 bytes
allocs estimate:  0
--------------
minimum time:     2.400 ms (0.00% GC)
median time:      2.414 ms (0.00% GC) …
```
=> sprinkle at-inline and at-propagate_inbounds around

docs/src/default_dict.md
with setup/repl macro
Closes #364
Helps #360 
Replaces #365
=> Improve DefaultDict doc

docs/src/ordered_containers.md, docs/src/sorted_containers.md
=> Remove straggling references to Associative

src/priorityqueue.jl, test/test_priority_queue.jl
Closes #434
Fix is quite trivial
Iterate without second argument also has to return a key-value pair.
=> Solve issue #434

docs/src/sorted_containers.md, src/balanced_tree.jl, src/container_loops.jl, test/runtests.jl, test/test_sorted_containers.jl
This commit rewrites container_loops.jl to incorporate the new iteration protocol
(introduced in 0.7.0-DEV) more thoroughly. It is not compatible with 0.6.
In addition, it fixes a bug in container_loops.jl in which the length()
function when applied to subranges (i.e., inclusive(a,b,c) or
exclusive(a,b,c)) returned the length of the whole container instead
of the length of the subrange. (There should be no value returned
for the length of the subrange since the data structure does not support
an O(1) algorithm or even O(log n) algorithm to compute the length.)
Some other smaller changes in this commit are as follows.
IntSet was changed to BitSet (name change in 0.7.0-DEV)
Small updates to documentation
Some assert statements in balanced_tree.jl that were present
during development are …
=> This commit updates container_loops.jl to use the new iteration protocol

src/priorityqueue.jl, test/test_priority_queue.jl
In addition to defining `empty!`, this makes `PriorityQueue` immutable. I don't see a reason it should be mutable, and indeed modifying its, e.g., ordering after filling it with items seems like a bad idea.
=> Define empty! for PriorityQueue

src/heaps/binary_heap.jl, src/heaps/mutable_binary_heap.jl, test/test_binheap.jl, test/test_mutable_binheap.jl
This fixes issue #399. That issue did not consider the case of updating a value in a mutable heap, but this PR contains a fix for that as well.
=> fix push! and update! for heaps to convert the input value

Project.toml, src/list.jl, test/test_list.jl
MWE: when there is a `LinkedList{Any}`, the following will error:
```julia
ex = :(a+b+2 * 2 + foo(2))
tl = list(ex.args...)
map(x->x, tl)
```
This PR will fix it, and will allow more generic (each node has different generic types) linked list.
=> fix identity map

docs/src/heaps.md, src/DataStructures.jl, src/heaps.jl, src/heaps/binary_heap.jl, src/heaps/mutable_binary_heap.jl, test/test_binheap.jl, test/test_mutable_binheap.jl
This PR addresses #469 by deprecating the old pseudoconstructors `(mutable_)binary_{min|max}heap` and replacing them with `(Mutable)Binary{Min|Max}Heap` constructors.
=> Update heap constructors

README.md, docs/src/accumulators.md, src/accumulator.jl, test/runtests.jl, test/test_accumulator.jl
needs tests
needs docs
Solves #474 
when documented will solve #133 
https://en.wikipedia.org/wiki/Multiset#Basic_properties_and_operations
It is tempting to define `zero(A::Type(<:Accumulator)=A()`
which would give us a group (in the mathematical sense).
If we are willing to think of `merge` and `setdiff` as the same operation, but one of which creating the inverse element.
=> Define multiset operations

README.md, docs/make.jl, docs/src/fenwick.md, src/fenwick.jl
Fix #491 and a positional change in docstring in `fenwick.jl`
=> Add documentation for FenwickTree

Project.toml, src/DataStructures.jl, src/priorityqueue.jl, test/test_priority_queue.jl
Ordered iterator interface for priority queues. 
The original unordered interface is preserved as that is used for most common functionalities like copying etc. This interface is a kind of a heapsort implementation but in place store has not been used.
=> Issue#369: Ordered iterator interface for priority queue

src/circular_buffer.jl
It was confusing since it said `pop` and `popfirst` both removed from the back.
I hope they don't.
=> Fix docstring on popfirst!(::CircularBuffer

src/circular_buffer.jl, src/deque.jl, src/disjoint_set.jl, src/fenwick.jl, src/heaps.jl, src/int_set.jl, src/list.jl, src/mutable_list.jl, src/queue.jl, src/sorted_set.jl, src/stack.jl, test/test_circ_deque.jl, test/test_circular_buffer.jl, test/test_deque.jl, test/test_disjoint_set.jl, test/test_fenwick.jl, test/test_int_set.jl, test/test_list.jl, test/test_minmax_heap.jl, test/test_mutable_binheap.jl, test/test_mutable_list.jl, test/test_queue.jl, test/test_stack.jl
Most of the containers did not have a defined `eltype` operation. I added it (or corrected the current implementation) for:
- `CircularBuffer`
- `Deque`
- `DisjointSet`
- `FenwickTree`
- `AbstractHeap`
- `IntSet`
- `LinkedList`
- `MutableList`
- `Queue`
- `SortedSet`
- `Stack`
Please let me know if I missed any. I purposefully avoided associative containers in this PR, though it should be defined for them as well. It makes sense to have a Key-Value associative container return `Pair{K, V}` from `eltype` similar to how `Dict` does it in Julia core.
=> Adding `eltype` for containers

src/trie.jl, test/test_trie.jl
Making `setindex!` work similarly to the standard library `Dict` and other containers. Now this works:
```julia
julia> T = Trie{Int64}()
Trie{Int64}(140018024147216, Dict{Char,Trie{Int64}}(), false)
julia> T["abc"] = 3
3
julia> T["def"] = Int8(5)
5
```
where before it failed.
=> Trie now converts val to the correct type

src/multi_dict.jl, test/test_multi_dict.jl
If merged closes #522.
Remove the automatic array appending functionality. Now arrays are treated as any other object.
Missing:
=> MultiDict - store arrays as arrays-of-arrays

.travis.yml, docs/make.jl
* Use Julia 1.2 for documentation build on travis
* Remove unnecessary/unused arguments to `deploydocs()`
Fixes #526
=> Update docs generation (minor)

.gitignore, .travis.yml, benchmark/Project.toml, benchmark/README.md, benchmark/benchmarks.jl, benchmark/pprinthelper.jl, benchmark/pprintjudge.jl, benchmark/runbenchmarks.jl, benchmark/runjudge.jl
This compares benchmark results of future PRs against master (just for heaps at this point). Note that this new benchmarking feature will not be fully operational until merged. An example of what to expect is in my [development branch](https://github.com/milesfrain/DataStructures.jl/pull/9).
The [results section of the Travis CI log](https://travis-ci.org/milesfrain/DataStructures.jl/jobs/589273895#L462) is where to look for regressions (excerpt below). There are no regressions in this case of updating the `readme`. An additional enhancement would be to automatically post a comment with this information to the PR (as is done with code coverage). Perhaps also mention the number non-overlaping baseline and target cases.
```
Results
=========
A ratio greater than 1.0 denotes a possible …
```
=> Use PkgBenchmark to detect performance regressions for heaps

src/queue.jl, test/test_queue.jl
These were missing from `Queue` but present in `Stack` and `Deque`.
=> Adding == and empty! for queue

src/stack.jl, test/test_stack.jl
Currently this fails unless the stacks are the same object in memory. All that was needed is a fallback to the deque storage `==` test.
=> Add == for stack

benchmark/README.md, benchmark/bench_heap.jl, benchmark/incrementalrunjudge.jl
This PR includes #545.
It should be rebased after the above is merged in order for CI to track benchmarking differences.
=> Expand benchmarking in anticipation of heap ordering change

src/sparse_int_set.jl
So far,  the inlining made the pop!/push! benchmark around 15% faster, the new iteration style improved the iteration speed with 25-30%. 
So far I don't see any other directly obvious speedups.
=> SparseIntSet speedups

src/classified_collections.jl
First part of #496  
I don't know what to recommend using instead.
Probably a `DefaultDict(Collection)`?
=> deprecate ClassifierCollection

docs/src/index.md
The documentation top page is missing contents about fenwick tree.
So I added it.
=> Add missing contents about fenwick tree for the documentation top page.

src/sorted_dict.jl, src/sorted_set.jl, test/test_sorted_containers.jl
The standard `Base.pop!` provides a 3-arg function:
```
pop!(h::Dict, key, default) in Base at dict.jl:608
```
This functionality is missing in `OrderedDict` and hence making it impossible to use `OrderedDict` as a drop-in replacement for `Dict`. This adds the missing functionality along with the unit tests.
=> Provide support for 3-arguments pop! for SortedDict to match Base.pop

Project.toml, src/disjoint_set.jl, test/test_disjoint_set.jl
Address error introduced by #567 in situations like the following:
```julia
DisjointSets(x % 2 == 0 ? x+1//x : x*im for x = 1:10)
```
=> Fix DisjointSets constructor error

src/accumulator.jl, test/test_accumulator.jl
fixes #573 
Made `Accumulator(2 => 2, 3 => 1, 1 => 2)` a valid constructor by accepting variable number of pairs as inputs and making dictionary out of them.
=> feat(accumulators.jl) : add constructor to Accumulator

src/accumulator.jl, src/balanced_tree.jl, src/circ_deque.jl, src/circular_buffer.jl, src/deque.jl, src/disjoint_set.jl, src/heaps.jl, src/heaps/arrays_as_heaps.jl, src/heaps/binary_heap.jl, src/heaps/minmax_heap.jl, src/heaps/mutable_binary_heap.jl, src/int_set.jl, src/list.jl, src/mutable_list.jl, src/priorityqueue.jl, src/queue.jl, src/robin_dict.jl, src/sorted_dict.jl, src/sorted_multi_dict.jl, src/sorted_set.jl, src/stack.jl, src/tokens2.jl, src/trie.jl
Multiline functions should use `return` for returning values.
PR is trivial enough.
I'll go through each of the files and try to spot if some part of the code violates standard. Gonna take a while. Bare through that period.
List of checked files.
- src/heaps
- robin_dict.jl
=> Update code as per Julia's community guidelines

src/DataStructures.jl, src/deprecations.jl, src/disjoint_set.jl, test/test_disjoint_set.jl
This allows the creation of type-parameterized `IntDisjointSets`, and keeps the default as `Int` for compatibility. (It also explicitly creates an `IntDisjointSets{Int}` for `DisjointSets`, which does not further type-specialize.)
=> type-parameterized IntDisjointSets

src/fenwick.jl, test/test_fenwick.jl
I think that `prefixsum(ft, x)` should give `0` when `x<1` instead of an ArgumentError, just like how `sum([12,3,4,5,6][1:0]) = 0`.
In particular I was editing some code, and I assumed that `sum(my_array[1:x]) == prefixsum(FenwickTree(my_array), x)` would always be `true`. I was surprised that it wasn't `true` for all `x`, and think that this should be changed.
=> prefixsum for non-positive index in FenwickTree

src/DataStructures.jl, src/deprecations.jl
@oxinabox @eulerkochy - I believe this addresses the change requests from #603.
If we could merge and tag this ASAP that would be much appreciated.  Some of my production code has been 10x slower since this change took effect.
CC @mlubin, @sbromberger
=> Restore find_root

src/sorted_dict.jl, src/sorted_set.jl, test/test_sorted_containers.jl
This makes SortedSet and SortedDict behave more like Julia Base's Set and Dict.
Fixes https://github.com/JuliaCollections/DataStructures.jl/issues/387
=> Change `delete!()` for Sorted{Set,Dict} to no-op if key not found.

Project.toml, src/sorted_set.jl
Have `SortedSet{K}` implement <: `AbstractSet{K}`. Fixes https://github.com/JuliaCollections/DataStructures.jl/issues/291.
Are there other things one needs to do to complete this? 
https://docs.julialang.org/en/v1/base/collections/
=> Make `SortedSet{K}` be a subtype of `AbstractSet{K}`.

src/deque.jl
Function names were changed in #565, but the docstrings for methods on `Deque` weren't updated
=> Fix `first` and `last` function names in `Deque` docstrings

docs/src/circ_deque.md
noticed that the description for push! and pushfirst! were duplicated
=> corrected description for CircularDeque push! function

src/DataStructures.jl
Removed in previous commit. Because of failure on nightlies.
=> Add export of peek to pass CI on Julia 0.7 and 1.0

docs/make.jl
`RobinDict` was not listed in the sidebar in docs even though it has a page and is listed in index under contents.
=> Add `RobinDict` to sidebar in docs

src/robin_dict.jl, test/test_robin_dict.jl
I believe without this change garbage keys from before `empty!` or garbage keys can be found in the dictionary which should be the case
=> RobinDict empty! not zeroing hashes bugfix

Project.toml, README.md, docs/make.jl, docs/src/dibit_vector.md, docs/src/index.md, src/DataStructures.jl, src/dibit_vector.jl, test/runtests.jl, test/test_dibit_vector.jl
After discussions with @eulerkochy I would like to merge this into DataStructures instead of keeping it as a separate package.
`DiBitVector` is a memory- and cache-friendly representation of values that are 2 bits wide. This has practical benefits to bioinformatics and graph analysis. For large vectors, use of a `DiBitVector` results in improved performance (due to cache locality) and 75% memory savings over a `Vector{UInt8}` (which is what we're currently using).
The selfish reason I have for asking for this to be incorporated into DataStructures.jl is because we already have DataStructures as a dependency for LightGraphs, and I'd like to use DiBitVector in our upcoming 2.0 version – but I don't want to add another dependency to LG, and I don't want to implement this directly in LG.
=> dibit_vector

Project.toml, src/robin_dict.jl, test/test_robin_dict.jl
Match to the behavior of `Base.Dict` in these scenarios.
Fixes #628
=> Correct the behavior of RobinDict for get, getkey, haskey, getindex

src/default_dict.jl
the fallback method seems to work just as well.
This method also causes some invalidations so good to get rid of it
cc @timholy (playing around with new SnoopCompile)
=> remove redundant iterate method

Project.toml, src/sorted_dict.jl, src/sorted_multi_dict.jl, src/sorted_set.jl, test/test_sorted_containers.jl
Per our notes in https://github.com/JuliaCollections/DataStructures.jl/pull/571#issuecomment-594125382, the sorted containers currently don't implement `Base.copy(x)`, which is "Strongly Recommended," but not "Required."
However, they do all already provide `packcopy(m)`, and as far as i can tell, that seems like a perfectly reasonable implementation of copy: it returns a new container with all the same elements but not necessarily the same structure. ✔️ 
So this PR simply aliases `copy` and `copymutable` to `packcopy`. Does that sound good? :)
Thanks!
~Nathan
=> Add Base.copy, Base.copymutable for Sorted containers

Project.toml, docs/src/trie.md, src/DataStructures.jl, src/deprecations.jl, src/trie.jl, test/runtests.jl, test/test_deprecations.jl, test/test_trie.jl
Closes #633 
should be merged before https://github.com/JuliaCollections/DataStructures.jl/pull/643
which will need to be rebased to delete this deprecation
=> deprecate path for partial_path

src/circ_deque.jl, src/circular_buffer.jl
Fills a few inbounds optimization gaps in ```CircularDeque``` and ```CircularBuffer``` implementations, adding missing propagation and eliminating redundant checks.
Benchmarked with
```Julia
using DataStructures
using BenchmarkTools
function pushpop(xs)
@inbounds push!(xs, 1)
@inbounds popfirst!(xs)
@inbounds pushfirst!(xs, 1)
@inbounds pop!(xs)
end
function pushpop_checked(xs)
push!(xs, 1)
popfirst!(xs)
pushfirst!(xs, 1)
pop!(xs)
end
@btime pushpop($(CircularDeque{Int}(10)))
@btime pushpop_checked($(CircularDeque{Int}(10)))
@btime pushpop($(CircularBuffer{Int}(10)))
@btime pushpop_checked($(CircularBuffer{Int}(10)))
```
| Test         | Container        | Before | After |
|-----------|-----------------|-------:|------:|
| pushpop | CircularDeque |  7.6ns | 2.3ns |
| pushpop_checked | …
=> inbounds optimizations for CircularDeque and CircularBuffer

.travis.yml, Project.toml, appveyor.yml, benchmark/bench_heap.jl, docs/src/heaps.md, src/DataStructures.jl, src/heaps.jl, src/heaps/arrays_as_heaps.jl, src/heaps/binary_heap.jl, src/heaps/minmax_heap.jl, src/heaps/mutable_binary_heap.jl, test/test_binheap.jl, test/test_minmax_heap.jl, test/test_mutable_binheap.jl
This merge sequence should be followed for generating useful benchmark comparisons:
1. #545 splits existing benchmarks into separate files
2. #546 adds more heap benchmarks
3. #547 makes significant heap changes
@oxinabox This change introduces API changes, and deprecation warnings should be added. Could we replace the previous deprecation warnings with a version bump?
=> Use Base.Ordering for heap, and other performance improvements

src/DataStructures.jl, src/robin_dict.jl, test/test_robin_dict.jl
This PR removes `include` statements in the file `src/robin_dict.jl` and moves them to the file `src/DataStructures.jl`, as per the convention followed in this codebase.
=> Remove import statement from robin_dict.jl

src/delegate.jl
These type annotations prevent invalidations due to packages that specialize `promote_rule`. The specific call signature, `promote_rule(::Type{Int64}, ::Type{S} where S)`, gets triggered by calls to `(::Colon)(::Int64, ::Real)`. Annotating these inputs as `Expr` allows inference to realize what the `args` field type is, thus allowing `length` to be inferred as returning an `Int`.
=> Improve inference for macros leading to (:)

.travis.yml, Project.toml, appveyor.yml, src/DataStructures.jl, src/deprecations.jl, test/test_deprecations.jl
Removing the `top` function broke a lot of code in the SciML ecosystem.
=> Add `top` alias

docs/src/stack_and_queue.md, src/DataStructures.jl, src/deprecations.jl, src/deque.jl, src/queue.jl, src/stack.jl, test/test_deprecations.jl, test/test_queue.jl, test/test_stack.jl
- trying out replacing `reverse_iter` with `Iterators.reverse` (not `reverse` since we don't promise to make a copy) -- thoughts?
- in the spirit of "No exported functions that could be just done with overloads of Base" (#479) 
- as commented in #479, I don't _think_ the `Iterators.reverse(::T) -> Iterators.Reverse{T}` is promised by the Iterators API, since it's not documented or tested for in Base (i.e. the changes of this PR don't break that API).
=> Deprecate `reverse_iter` to `Iterators.reverse`

Project.toml, docs/src/heaps.md, src/heaps.jl, src/heaps/binary_heap.jl, src/heaps/mutable_binary_heap.jl, test/test_binheap.jl, test/test_mutable_binheap.jl
* Added constructors to `BinaryHeap` and `MutableBinaryHeap` that take a `Base.Ordering` instance as the first argument. Previously the only way to use a specific ordering was as a type parameter, which only works if the ordering type is a singleton/has a constructor with no arguments.
* Modified `nlargest` and `nsmallest` signatures to take `by` and `lt` arguments as in `sort`. This shouldn't incur a performance penalty as I'm pretty sure Julia can fully specialize on keyword arguments, and the default argument values should statically resolve to calling `nextreme` with either `Base.Forward` or `Base.Reverse`.
* Updated docs page with instructions on how to use these features.
=> Use custom orderings with heaps and nlargest/nsmallest

Project.toml, src/heaps/mutable_binary_heap.jl, test/test_mutable_binheap.jl
Added test where a 3-element MutableBinaryMinHeap is created and last
element is deleted. This test failed as reported in #678.
This test failure was fixed by not swapping and bubbling when the last
element in a heap is deleted.
Please review and hit me with all problems you see.
=> Fix #678 BoundsError in MutableBinaryHeap delete! with 3 elements

Project.toml, src/heaps/binary_heap.jl, test/test_binheap.jl
Fixed #686 
Would be cleaner if we had https://github.com/JuliaLang/julia/pull/37822
=> Fix BinaryMaxHeap type alias

Project.toml, src/deque.jl, test/bench_deque.jl
As reported in at least issue https://github.com/JuliaCollections/DataStructures.jl/issues/619, iterating over `Deque` was type unstable. This also therefore extends to `Queue` and `Stack` which are based on `Deque`. Running your benchmark (and a new `sum` benchmark) gives the following 75x speed-up of iteration.
Before:
```
traverse 10^7 integers:
Vector:   elapsed =   0.0000s
Deque:    elapsed =   0.3877s
sum 10^7 integers:
Vector:   elapsed =   0.0044s
Deque:    elapsed =   0.5728s
```
After:
```
traverse 10^7 integers:
Vector:   elapsed =   0.0000s
Deque:    elapsed =   0.0051s
sum 10^7 integers:
Vector:   elapsed =   0.0036s
Deque:    elapsed =   0.0085s
```
=> Fixed type-instability in Deque iterator

README.md, docs/make.jl, docs/src/disjoint_set.md, src/DataStructures.jl, src/deprecations.jl, src/disjoint_set.jl, test/test_disjoint_set.jl
Addresses #694 and resolves error when pushing a repeated element to a `DisjointSet`:
```julia
julia> ds = DisjointSets('a':'e')
DisjointSets{Char} with 5 elements:
'a'
'b'
'c'
'd'
'e'
julia> ds.intmap
Dict{Char,Int64} with 5 entries:
'a' => 1
'c' => 3
'd' => 4
'e' => 5
'b' => 2
julia> ds.internal
IntDisjointSets{Int64}([1, 2, 3, 4, 5], [0, 0, 0, 0, 0], 5)
julia> push!(ds, 'b')
'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
julia> ds.intmap
Dict{Char,Int64} with 5 entries:
'a' => 1
'c' => 3
'd' => 4
'e' => 5
'b' => 6
julia> ds.internal
IntDisjointSets{Int64}([1, 2, 3, 4, 5, 6], [0, 0, 0, 0, 0, 0], 6)
```
=> Rename DisjointSet and resolve errors

src/heaps/arrays_as_heaps.jl, src/heaps/binary_heap.jl, src/heaps/mutable_binary_heap.jl, test/test_mutable_binheap.jl
Issue with `Base.Order.ReverseOrdering`. Mirror of #686, only related to a `MutableBinaryHeap` implementation. Depends on https://github.com/JuliaLang/julia/pull/37822.
=> Fix MutableBinaryHeap, issue similar to #686

src/mutable_list.jl, test/test_mutable_list.jl
Fixes #725 
The logic for making the end of the appended list point to the original list's terminal node was wrong.
=> Fix MutableLinkedList append! w/ test

docs/src/default_dict.md
Seems like a useful example to include. Alternatively I could see a `DefaultDictRec` being introduced which could be an abstraction on this idea and would allow for dynamically setting the type parameters.
=> Add recursive `DefaultDict` example

Project.toml, src/default_dict.jl, test/test_default_dict.jl
I wanted both of these things (the documentation and these particular constructors) this evening. I didn't document _all_ the available constructors, just the four that I wanted as I think those are the most commonly tread path.
=> Document Default*Dict and add Default*Dict{K,V} constructors

docs/src/stack_and_queue.md, src/deprecations.jl, src/queue.jl, test/test_deprecations.jl, test/test_queue.jl
Attempt number two. I think I covered everything.
=> Change enqueue! dequeue! to push! popfirst!

src/circular_buffer.jl, test/test_circular_buffer.jl
Adds constructors to Circular Buffer allowing a vector or other iterable to be in the buffer once initialized. Capacity is still required to be provided by the user and errors if the given capacity is less than the length of the given iterable. If no type parameter is given the eltype of the provided iterable is used. If one is provided the provided iterable is converted to that type (if possible, errors otherwise).
Existing constructors have changed slightly via new type restrictions.
Allows:
`CircularBuffer(1:5,10)`
`CircularBuffer{Float64}([1,2],100)`
`CircularBuffer((1,2.0,"hi"),20)`
=> Circ buff new constructor

src/heaps/minmax_heap.jl, test/test_minmax_heap.jl
Hi there! I was recently working on a project making heavy use of the min-max heap and found some performance improvements (primarily ditching allocating a particular array in `children_and_grandchildren`). You can checkout a benchmark below. Note, this does make a change to the return type of an internal method. Thanks for the great package and I'm happy to make any necessary changes!
```julia
using DataStructures, Random
function test(
h::DataStructures.BinayMinMaxHeap;
maxlen = 10000,
percent_push = 0.5,
percent_pop_min = 0.5,
max_consecutive = 100,
numtests = 1_000_000,
)
Random.seed!(12345)
for _ in 1:numtests
if rand() <= percent_push
num_to_push = rand(1:max_consecutive)
for _ in 1:num_to_push
length(h) == maxlen && break
push!(h, rand(Int64))
end
elseif rand() <= percent_pop_min …
```
=> Performance improvements to BinaryMinMaxHeap

src/priorityqueue.jl, test/test_priority_queue.jl
There are no large consequences here, just mostly janitorial. There is one functional change represented by the new test, that `dequeue!(pq, key)` is now guaranteed to return something of `keytype(pq)` (rather than just `key` directly). I *think* that's the right thing to do, but it probably already happens for the large majority of uses even without this precaution.
=> Minor cleanups & performance enhancement

docs/src/trie.md, src/DataStructures.jl, src/trie.jl, test/test_trie.jl
This PR improved `Trie` with the following two points.
1. fix `TrieIterator` to correctly handle non-ascii characters
2. add `find_prefixes` function which is equivalent to `prefixes` method of https://github.com/pytries/marisa-trie
=> Improvements of Trie Structure

src/sorted_set.jl
to avoid false positive by JET.@report_opt
```
using DataStructures
using JET
struct FP
a::Int
end
Ordering = Lt( (fp1::FP, fp2::FP) -> fp1.a < fp2.a)
@report_opt SortedSet{FP}(Ordering )
═════ 1 possible error found ═════
┌ @ /home/wsl/.julia/packages/DataStructures/nBjdy/src/sorted_set.jl:71 Core.apply_type(DataStructures.SortedSet, _, _)(o)
│┌ @ /home/wsl/.julia/packages/DataStructures/nBjdy/src/sorted_set.jl:22 #self#(o, Base.vect())
││┌ @ /home/wsl/.julia/packages/DataStructures/nBjdy/src/sorted_set.jl:130 DataStructures.convert(FP, %23)
│││ runtime dispatch detected: DataStructures.convert(FP, %23::Any)
││└────────────────────────────────────────────────────────────────────────
```
=> type default argument in SortedSet constructor

docs/src/priority-queue.md, src/DataStructures.jl, src/deprecations.jl, src/priorityqueue.jl, test/test_deprecations.jl, test/test_priority_queue.jl
I took a stab at the remaining part of #296. Please note my [comment on discourse](https://discourse.julialang.org/t/taking-push-and-pop-seriously/34326/20?u=jonas-schulze) on instead using `put!` and `take!`, but I think a consistent API is more important now.
If the refactor of `popfirst!` to match `eltype` went too far (*breaking change*), I can drop the corresponding commit. Also, I for now deprecated `enqueue(pq, key, val)` in favor of `Base.push!(pq, key=>val)` instead of `Base.insert!(pq, key, val)`. Less is more, I think. `Dict` doesn't have `push!` nor `insert!`.
This is ready for comments, but there are some parts missing:
Close #296
=> Deprecate enqueue!, dequeue! and peek for PriorityQueue

src/DataStructures.jl, src/avl_tree.jl, src/red_black_tree.jl, src/splay_tree.jl, test/runtests.jl, test/test_avl_tree.jl
Improves benchmark results for
https://github.com/JuliaCollections/DataStructures.jl/issues/762
v0.18.10
100000 elements
DataStructures.AVLTree                   6.061 s (7102520 allocations: 114.48 MiB)
1000 elements
DataStructures.AVLTree                   36.800 ms (28637 allocations: 509.97 KiB)
10 elements
DataStructures.AVLTree                   134.361 μs (102 allocations: 2.23 KiB)
v0.19.0-DEV
100000 elements
DataStructures.AVLTree                   6.113 s (7102520 allocations: 114.48 MiB)
1000 elements
DataStructures.AVLTree                   36.298 ms (28637 allocations: 509.97 KiB)
10 elements
DataStructures.AVLTree                   130.629 μs (102 allocations: 2.23 KiB)
Now:
100000 elements
DataStructures.AVLTree                   213.450 ms (200002 allocations: 9.16 MiB) …
=> Fix type instabilities in AVL, RB and splay tree

src/heaps/arrays_as_heaps.jl
I was playing around with the arrays_as_heaps code, and I think this is ever so slightly cleaner.
=> Cleaner percolate up/down syntax

README.md, docs/make.jl, docs/src/disjoint_sets.md
This is a docs-only PR to change occurrences of "disjoint set" to "disjoint sets" in the docs. Should close #740.
This also happens to fix a slight bug that the table of contents didn't show the page for Disjoint Sets, since the name of link was changed (but the name of the actual doc file was not yet changed).
=> Fix docs: switch "disjoint set" to "disjoint sets" in docs

docs/src/deque.md, src/deque.jl
Hello!
This is the first of a series of PRs aiming to dramatically improve the current documentation of DataStructures.jl.
Some of the changes include the addition of actual documentation generated by Documenter.jl from docstrings (see `docs/src/deque.md`), a brief explanation of the Deque data structure and a few minor changes in source code.
The new documentation page formats will be structured in the following manner:
1. Data structure description and characteristics.
2. Constructors for the implemented data structure
3. Usage, showing first a list of available methods for the given data structure sorted alphabetically, followed by the Documenter.jl generated documentation.
Let me know in case of any suggestions.
=> Improved Deque Documentation + docstrings

README.md
- Replaces https://juliacollections.github.io/DataStructures.jl/latest (which actually points to the dev docs) with a link to the stable docs version.
- Adds badges for stable and dev docs.
=> Include URLs for dev and stable docs in README

src/sorted_container_iteration.jl
I didn't check, but unbound type parameters often cause performance issues, so this isn't merely cosmetic.
FTR, there's a relevant function in Test in stdlib for checking this stuff:
https://docs.julialang.org/en/v1/stdlib/Test/#Test.detect_unbound_args
=> remove unbound type parameters

test/test_int_set.jl
This apparently breaks the tests on 1.9. No idea why they are there in the first place.
=> remove resizing of internal fields in int set tests

docs/Project.toml, src/ordered_robin_dict.jl, src/priorityqueue.jl, src/robin_dict.jl, src/stack.jl, src/swiss_dict.jl
=> Update the version of Documenter.jl

docs/src/disjoint_sets.md
I was doing Advent of Code and had trouble finding this function, so I think it should be in the documentation. As an aside, not sure if it should say "return the number of _groups_" or the number of _sets_.
=> Add num_groups for DisjointSets to documentation

src/ordered_robin_dict.jl, test/runtests.jl, test/test_ordered_robin_dict.jl
Resolves #857 
I am not sure if checking if the key appears in the key vector property is the right way to go. Open to another solution!
=> fix: check key values, not `get` return for haskey(k, orderedrobindict)

src/accumulator.jl
=> Permit non-number types in Accumulator

src/accumulator.jl, test/test_accumulator.jl
Previously the `Accumulator(::Pairs...)` constructor first converted the sequence to a `Dict`, thus dropping repeated keys, which seemed counter what I would expect an accumulator to do (e.g. when used with a generator).
=> do not drop repeat keys in Accumulate(::Pairs...)

src/sorted_dict.jl, src/sorted_set.jl
Like #854 but with `eltype` removed also for `SortedSet`.
Do we need to do the same for `keytype` of `SortedSet`, which is not normally defined for `AbstractSet`?
xref: https://github.com/JuliaCollections/DataStructures.jl/pull/854#issuecomment-1656749953
=> remove eltype definition from SortedDict and SortedSet

src/mutable_list.jl, test/test_mutable_list.jl
See https://github.com/JuliaCollections/DataStructures.jl/issues/739 for example of the segfault that I'm seeing
- Updates `Base.append!(l1::MutableLinkedList{T}, l2::MutableLinkedList{T}) where T` so that the resulting object doesn't print endlessly to the screen, and that `collect` doesn't segfault the julia session
- adds more lines to update node `next` and `prev` pointers
- Adds a test in the append section so that the second argument is checked for being empty
with these changes, I'm seeing this work without segfaulting
```julia
(@v1.9) pkg> activate .
Activating project at `~/repos/DataStructures.jl`
julia> using DataStructures
julia> l1, l2 = MutableLinkedList{Int}(1,2), MutableLinkedList{Int}(3,4)
(MutableLinkedList{Int64}(1, 2), MutableLinkedList{Int64}(3, 4))
julia> append!(l1, …
```
=> Fix for MutableLinkedList append!

.github/workflows/CI.yml, Project.toml, src/DataStructures.jl, src/priorityqueue.jl
- Includes https://github.com/JuliaCollections/DataStructures.jl/pull/844 to "get rid of Compat dependency and bump Julia compat to 1.6"
- Cleaned up the exports, though I'm not sure about `peek`
=> Use Julia 1.6 as new minimum

Project.toml
The compat dependency isn't needed anymore
=> remove compat dependency

test/test_sorting.jl
These belong in OrderedCollections.jl if anywhere, but the functionality is deprecated and hopefully will be removed soon. Xref https://github.com/JuliaCollections/OrderedCollections.jl/pull/110#issuecomment-1837216764
=> remove tests for `sort(::Dict)`

src/mutable_list.jl, test/test_mutable_list.jl
Currently `append!(MutableLinkedList{Int}(), [3])` would try to push the vector into the linked list instead of pushing elements into the linked list.
=> fix append! iterable to MutableLinkedList

src/deque.jl, test/test_deque.jl
=> Empty head block's data when the block is reset

.gitignore, src/circ_deque.jl, src/circular_buffer.jl, src/deque.jl
This PR aims to solve https://github.com/JuliaCollections/DataStructures.jl/issues/891, and check if this issue occurs for other types as well. For the types listed [in the documentation](), the results are seen in the drop-down below.
<details>
Deque (implemented with an unrolled linked list)
errors on `Deque{Float64}(Int32(10))`. Fixed
CircularBuffer
Silent error on CircularBuffer{Float32}(Int32(10)). Fixed
CircularDeque (based on a circular buffer)
errors on CircularDeque{Float32}(Int32(10)). Fixed
Stack
errors on Stack{Float64}(Int32(5)). Got fixed, I think with Deque
Queue
errors on Queue{Float64}(Int32(5)). Got fixed, I think with Deque
Priority Queue
No length parameter upon initialization
Fenwick Tree
Works for FenwickTree{Float64}(Int32(5)) and FenwickTree{Float64}(Int16(5))
No …
=> Allow other int types for type container size

.github/workflows/CI.yml, src/circ_deque.jl, src/deque.jl, test/test_circ_deque.jl, test/test_deque.jl
For `Deque` and `CircularDeque`. So that popped elements are not rooted by the deque and can be GCed when they drop out of caller scope.
Completes the fix of #884.
=> Use `Base._unsetindex!` in `pop!` and `popfirst!`

Project.toml, src/DataStructures.jl, src/circ_deque.jl, src/deque.jl, test/test_circ_deque.jl, test/test_deque.jl
- backport #897 to v0.18 (fixes #884)
cc @kpamnany
=> Backport deque memory fix

src/circular_buffer.jl
As suggested in [this](https://github.com/JuliaCollections/DataStructures.jl/issues/894#issuecomment-1925922689) comment in #894
=> Conditional import of Base.isfull

src/accumulator.jl, src/circular_buffer.jl
- `Base.keys()` already works on `AbstractDict`'s so we don't need one for `Accumulator`.
- `Base.eltype()` is already defined for `AbstractArray`'s and `CircularBuffer` is an `AbstractVector` so it doesn't need to define it again.
- A `Base.convert()` method from `AbstractArray` to `Array` is already defined: https://github.com/JuliaLang/julia/blob/1ae41a2c0a3ba49d4b39dc4933dddf952b5f7f3c/base/array.jl#L612
I found these through looking at invalidations from Dagger.jl (CC @jpsamaroo). Before:
```julia
julia> include("test/invalidations.jl")                                                                                                                                                                                                        
Precompiling Dagger …
```
=> Delete unnecessary methods to fix invalidations

Project.toml, src/accumulator.jl, src/circular_buffer.jl
As discussed in https://github.com/JuliaCollections/DataStructures.jl/pull/904#issuecomment-2051601857.
=> Backport invalidation fixes to 0.18.19

src/heaps/arrays_as_heaps.jl, src/heaps/binary_heap.jl
Noticed that sizehint! was actually worsening a lot of the performance of some of my heaps, with this change it is much faster:
e.g. with
```julia
using DataStructures, BenchmarkTools
function with_sizehint(T, n)
value = BinaryHeap(Base.Order.ForwardOrdering(), T[])
sizehint!(value, n)
end
```
before:
```julia
julia> @btime with_sizehint(Int, 1);
861.250 ns (5 allocations: 256 bytes)
```
after:
```julia
julia> @btime with_sizehint(Int, 1);
64.790 ns (4 allocations: 224 bytes)
```
=> Improve performance of sizehint! on BinaryHeap

README.md
No more Travis & AppVeyor, instead GitHub CI
=> README.md: update CI badges

src/DataStructures.jl
Hi,
In the current version 0.18.20 of DataStructures, using `dequeue!` leads to runtime dispatches affecting performance.
The error can be fixed by declaring a used alias as const.
Small example reproducing the error:
```Julia
using JET
using Pkg
Pkg.activate(".")
using DataStructures
q = Queue{Int}()
enqueue!(q, 1)
@report_opt dequeue!(q)
```
results in 
´´´
═════ 1 possible error found ═════
┌ dequeue!(s::Queue{Int64}) @ DataStructures /home/marius/repos/DataStructures.jl/src/queue.jl:37
│┌ popfirst!(q::Deque{Int64}) @ DataStructures /home/marius/repos/DataStructures.jl/src/deque.jl:305
││ runtime dispatch detected: %33::Any(%34::Vector{Int64}, %35::Int64)::Any
│└────────────────────
´´´
=> Fix runtime dispatch in Deque

.github/workflows/CI.yml, .github/workflows/Documenter.yml, docs/make.jl
=> CI: run doctests to catch regressions; test against Julia LTS; allow julia-actions/cache to cleanup caches

docs/src/heaps.md, src/heaps.jl, src/heaps/binary_heap.jl, src/heaps/mutable_binary_heap.jl, test/test_binheap.jl, test/test_mutable_binheap.jl
The PR adds definitions of `empty!(::BinaryHeap)` and `empty!(::MutableBinaryHeap)`.
Fixes https://github.com/JuliaCollections/DataStructures.jl/issues/866.
=> Define `empty!` for `BinaryHeap` and `MutableBinaryHeap`

src/stack.jl
this will just work with a vector I think
cc @oscardssmith
=> Remove outdated Iterators.reverse definition

Project.toml, src/dict_support.jl, test/test_priority_queue.jl
Jeff and Oscar agree this should be equivalent (and precompilable!).  It uses Base.isiterable instead.
This also adds a fast path checking `eltype` if at all possible.  Only if the eltype is not Any do we use the fast path.  But that should ideally also cut down the time taken to construct a priority queue.
=> Refactor `not_iterator_of_pairs` to stop using `InteractiveUtils`

CHANGELOG.md, Project.toml
It's been nearly 5 years since the last release, so let's definitely release a new version.
This release appears to be quite breaking. I used CLAUDE to write release notes that follow the [Keep a
changelog](https://keepachangelog.com/en/1.1.0/) format.
=> release v0.19
